### ISSUE TITLE
guava should be marked as runtime dependency

### ISSUE THREAD

**Issue by mmfundament** [Ecwid/maleorang#11]
When using the latest 3.0-0.9.5 from maven central repo. I get this runtime exception. It's seems guava should be a runtime dependency instead of just compile time.

java.lang.NoClassDefFoundError: com/google/common/reflect/TypeToken

	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:455)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:367)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.ecwid.maleorang.MailchimpMethod.<init>(MailchimpMethod.kt:16)

**Comment by basiliscus** [comment]
Hi @mmfundament ,

Not sure why you face this issue. Every compile time dependency is a runtime dependency as well. That can be proved by the following command in the project root:
`gradle dependencies --configuration=runtime`
