### ISSUE TITLE
NoSuchFieldError

### ISSUE THREAD

**Issue by momoterzu** [Ecwid/maleorang#25]
I've always encountered this error while running the app 

`2018-Apr-30 17:07:41 PM [https-jsse-nio-8443-exec-4] ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/ULFWS].[dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with path [/ULFWS] threw exception [Handler dispatch failed; nested exception is java.lang.NoSuchFieldError: INSTANCE] with root cause
java.lang.NoSuchFieldError: INSTANCE
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.<clinit>(SSLConnectionSocketFactory.java:146) ~[httpclient-4.5.3.jar:4.2.3]
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.getDefaultRegistry(PoolingHttpClientConnectionManager.java:115) ~[httpclient-4.5.3.jar:4.2.3]
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.<init>(PoolingHttpClientConnectionManager.java:122) ~[httpclient-4.5.3.jar:4.2.3]
	at com.ecwid.maleorang.connector.HttpClientConnector.<clinit>(HttpClientConnector.kt:66) ~[maleorang-3.0-0.9.6.jar:?]
	at com.ecwid.maleorang.MailchimpClient.<init>(MailchimpClient.kt:25) ~[maleorang-3.0-0.9.6.jar:?]`

I already tried adding httpclient and httpcore in maven dependencies,  but the error still appears.

here is a list of my dependencies : 
`<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter</artifactId>
			<exclusions>
				<exclusion>
					<groupId>org.springframework.boot</groupId>
					<artifactId>spring-boot-starter-logging</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-aop</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-security</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-tomcat</artifactId>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.springframework.security</groupId>
			<artifactId>spring-security-test</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-jdbc</artifactId>
		</dependency>
		<dependency>
			<groupId>mysql</groupId>
			<artifactId>mysql-connector-java</artifactId>
			<version>5.1.6</version>
		</dependency>
		<dependency>
			<groupId>org.springframework.security.oauth</groupId>
			<artifactId>spring-security-oauth2</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.security</groupId>
			<artifactId>spring-security-jwt</artifactId>
			<version>1.0.0.RELEASE</version>
		</dependency>
		
		<dependency>
			<groupId>com.google.code.gson</groupId>
			<artifactId>gson</artifactId>
			<version>2.8.0</version>
		</dependency>
		<dependency>
			<groupId>io.swagger</groupId>
			<artifactId>swagger-core</artifactId>
			<version>1.5.8</version>
		</dependency>
		<dependency>
			<groupId>io.jsonwebtoken</groupId>
			<artifactId>jjwt</artifactId>
			<version>0.6.0</version>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-log4j2</artifactId>
		</dependency>
		<dependency>
		    <groupId>com.ecwid</groupId>
		    <artifactId>maleorang</artifactId>
		    <version>3.0-0.9.6</version>
		</dependency>
	</dependencies>`

DId i miss something here?

**Comment by momoterzu** [comment]
Found it, conflict on dependency.
